### PR TITLE
Add more containerd logs

### PR DESCRIPTION
**Pull request by kiashok**
What type of PR is this?

/kind bug

What this PR does / why we need it:

Which issue(s) this PR fixes:
Adds '--pids' option to shimdiag.exe log collection
Collects logs from hcsdiag.exe tool

Fixes #

Special notes for your reviewer:

Release note:
**Release note**:
```
none
```

### CODE REVIEW

**Comment by kiashok** [comment]
cc @chou @ShiqianTao  @junjiezhang1997

**Comment by kiashok** [comment]
@AbelHu @ShiqianTao  could you please take a look? Thanks!

**Comment by kiashok** [comment]
> @AbelHu @ShiqianTao could you please take a look? Thanks!

This has been verified on AKS windows cluster:

image


Could you please take a look and merge PR if things look good please? Thanks!

**Review by AbelHu — APPROVED** [review]
LGTM. Thanks for the PR.

**Pull request merged**
