### PR TITLE
Add new versions of metrics server

### PR DESCRIPTION
**Pull request by AYM1607**
Adds versions that are now being used in _images.tpl in RP and removes unused ones.

**What type of PR is this?**

**What this PR does / why we need it**:

We're updating the patch versions used in RP as well as introducing a new version for k8s 1.24 preview.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by robbiezhang — APPROVED** [review]

**Comment by AYM1607** [comment]
@ganeshkumar5699 it seems that some pipelines are failing because 1.24 cannot be downloaded, could it be related to #1796 ? The specific error is
```
Curl exited with '23' while attemping to download 'https://acs-mirror.azureedge.net/kubernetes/v1.24.0/windowszip/v1.24.0-1int.zip'
```

**Comment by ganeshkumar5699** [comment]
> 

That's interesting: the Windows VHD test pipelines did succeed for my PR to add 1.24.0 in Windows VHDs: https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=55169551&view=results.

**Comment by ganeshkumar5699** [comment]
The download URL is also valid (just checked that it downloads)

**Comment by ganeshkumar5699** [comment]
@AYM1607, I went through the Windows logs and I wonder if it's due to space constraint for Windows VHDs (cc: @AbelHu, @ShiqianTao could help clarify)?

Found this in the Windows VHD logs (link): https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=55225217&view=logs&j=26d3b11b-de37-5bdb-7f8b-686d226a8fb0&t=73630cad-3f30-5fb3-16e6-4f2994f8a555&l=1710

 azure-arm:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    azure-arm:                                  Dload  Upload   Total   Spent    Left  Speed
    azure-arm:
    azure-arm:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    azure-arm:  93 57.3M   93 53.4M    0     0   196M      0 --:--:-- --:--:-- --:--:--  196M
    azure-arm:  94 57.3M   94 54.3M    0     0   197M      0 --:--:-- --:--:-- --:--:--  197M
    **azure-arm: curl: (23) Failure writing output to destination**
    azure-arm: 2022-05-11T02:03:05.8933243+00:00: Get Disk info
    azure-arm: 2022-05-11T02:03:06.1589588+00:00: **Disk C: Free space: 602112, Total size: 31686914048**


The free space seems to be less that the space of the downloaded file and the write action may fail because of that. 


cc: @alexeldeib

**Comment by AbelHu** [comment]
@ganeshkumar5699 This PR is not related to Windows so you can ignore the failure in Windows VHD build. It seems like that the space of the disk for 2019 docker is not enough. We will check it.

**Review by AbelHu — APPROVED** [review]

**Comment by AYM1607** [comment]
it seems like I don't have write access to the repo, I'll try to get that sorted out, @AbelHu could you help by merging in the meantime?

**Pull request merged**
