### PR TITLE
vendor + update previous commit

### PR DESCRIPTION
**Pull request by alexeldeib**
whoops, sorry :(

### CODE REVIEW

**Comment by alexeldeib** [comment]
@xuto2 I guess after this merges we would need to bump AgentBaker in RP too?

**Comment by alexeldeib** [comment]
I've prepared the pull request with the RP toggle and compared it against this branch for testing purposes, if you're able to cut a tag when this merges that would be great!

**Comment by xuto2** [comment]
@alexeldeib use tag v0.0.32 if you need to vendor

**Pull request merged**
