### PR TITLE
chore: remove list permission and redact token in logs

### PR DESCRIPTION
**Pull request by AbelHu**
**What type of PR is this?**
/kind: build

**What this PR does / why we need it**:
1. remove list permission
2. redact token in logs

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by AbelHu** [comment]
cc @alexeldeib @ganeshkumar5699 `vhdbuilder/packer/generate-vhd-publishing-info.sh` is used by both Windows and Linux so please help to take a look at it.

**Review by ShiqianTao — APPROVED** [review]

**Comment by ganeshkumar5699** [comment]
Just to confirm, was this tested with a build to make sure the change works as expected?

**Comment by ganeshkumar5699** [comment]
We used to copy this URL for PIR publishing and after we stopped publishing to PIR, I don't think this URL has been useful. Perhaps it may be useful if we are asked to publish to PIR again (doubtful) or for debugging (image replication issues can usually be debugged through the portal so it should be ok), but it seems unlikely. 

Thanks for noticing this. Lgtm.

**Comment by ganeshkumar5699** [comment]
just icymi, found these logs with suggestions in `check-generated`from shell-shell (ex: https://github.com/koalaman/shellcheck/wiki/SC2001): 

> redact_vhd_url=$(echo $vhd_url |sed -e 's/?.*/?***/')
>                  ^-- SC2001: See if you can use ${variable//search/replace} instead.
> 
> 
> make: *** [Makefile:93: generate] Error 2
> In ./vhdbuilder/packer/generate-vhd-publishing-info.sh line 63:
> cat vhd-publishing-info.json | sed 's/?.*\",/?***\",/g'
>     ^----------------------^ SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
> 
>

**Review by ganeshkumar5699 — APPROVED** [review]
Lgtm besides the couple of small comments above about testing + check-generated suggestion. Thank you!

**Comment by AbelHu** [comment]
> ments above about testing + check-generated suggestion.

I have manually tested redact commands. I do not validate the SAS token with removing the SAS token since it needs to publish a new SIG image. We can revert this PR if we hit any issue. That is why I need to involve you :), @ganeshkumar5699.

**Comment by AbelHu** [comment]
Thanks for the reminder, @ganeshkumar5699 . I have updated it in https://github.com/Azure/AgentBaker/pull/1771/commits/1ba18fd51e7b9e6872387f03587974eecc1fc71c


> just icymi, found these logs with suggestions in `check-generated`from shell-shell (ex: https://github.com/koalaman/shellcheck/wiki/SC2001):
> 
> > redact_vhd_url=$(echo $vhd_url |sed -e 's/?._/?_**/')
> > ^-- SC2001: See if you can use ${variable//search/replace} instead.
> > make: *** [Makefile:93: generate] Error 2
> > In ./vhdbuilder/packer/generate-vhd-publishing-info.sh line 63:
> > cat vhd-publishing-info.json | sed 's/?._",/?_**",/g'
> > ^----------------------^ SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.

**Pull request merged**
