### PR TITLE
feat: container insights release 3.1.22 and win-3.1.22

### PR DESCRIPTION
**Pull request by wanlonghenry**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:

```
none
```

### CODE REVIEW

**Review by ganga1980 — APPROVED** [review]

**Review by djsly — APPROVED** [review]

**Review by junjiezhang1997 — COMMENTED** [review]
@cameronmeissner Linux pipelines failed due to capacity issue in eastus. Could you please take a look?

**Comment by djsly** [comment]
> @cameronmeissner Linux pipelines failed due to capacity issue in eastus. Could you please take a look?

@junjiezhang1997  we are working on changing the Packer build azure location outside of the affected eastus, until this is completed, the pipeline tests will be flaky

**Review by cameronmeissner — APPROVED** [review]

**Comment by junjiezhang1997** [comment]
> > @cameronmeissner Linux pipelines failed due to capacity issue in eastus. Could you please take a look?
> 
> @junjiezhang1997 we are working on changing the Packer build azure location outside of the affected eastus, until this is completed, the pipeline tests will be flaky

**Review by djsly — APPROVED** [review]

**Comment by cameronmeissner** [comment]
any reason we're still waiting to merge?

**Pull request merged**
