### PR TITLE
feat(wasm): remove slight and wws shims and use SpinKube spin shim

### PR DESCRIPTION
**Pull request by Mossaka**
**What type of PR is this?**
/kind feature
/kind deprecation

**What this PR does / why we need it**:

This PR removes the `slight` and `wws` shims from AKS WASI Nodepool. It also swaps the Spin shim from Deislabs to SpinKube org. 

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:

```
none
```

### CODE REVIEW

**Review by juan-lee — APPROVED** [review]
lgtm

**Comment by Mossaka** [comment]
I have ran `e2e-local.sh` it looks that all the tests have passed

```shell
./e2e/e2e-local.sh 
+ : 90m
+ : 100
+ go version
go version go1.22.5 darwin/arm64
+ go test -parallel 100 -timeout 90m ./...
?       github.com/Azure/agentbaker/apiserver   [no test files]
?       github.com/Azure/agentbaker/cmd [no test files]
?       github.com/Azure/agentbaker/cmd/starter [no test files]
?       github.com/Azure/agentbaker/fuzz/api    [no test files]
?       github.com/Azure/agentbaker/parts       [no test files]
?       github.com/Azure/agentbaker/pkg/agent/toggles/fieldnames        [no test files]
ok      github.com/Azure/agentbaker/pkg/agent   5.061s
ok      github.com/Azure/agentbaker/pkg/agent/common    0.627s
ok      github.com/Azure/agentbaker/pkg/agent/datamodel 0.474s
ok      github.com/Azure/agentbaker/pkg/agent/toggles   1.116s
ok      github.com/Azure/agentbaker/pkg/proto/nbcontract/v1     0.738s
ok      github.com/Azure/agentbaker/pkg/vhdbuilder/datamodel    0.949s
```

**Comment by cameronmeissner** [comment]
I think we'll need to tweak these changes to _only_ add the new runtime and keep the originals, after we've released these changes and the corresponding RP changes we can then safely remove the existing runtime classes

**Comment by Mossaka** [comment]
@cameronmeissner good idea, I've created a new PR #4744 that addresses your concern, namely that the new PR does not introduce breaking changes, only upgrades to the spin shim. I am going to close this PR and move the conversation to there.

**Pull request closed without merging**
