### PR TITLE
chore: upgrade Azure Disk CSI driver to v1.15

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
chore: upgrade Azure Disk CSI driver to v1.15
This PR also updates old windows csi driver images with new ones.

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
chore: upgrade Azure Disk CSI driver to v1.15
```

### CODE REVIEW

**Review by mainred — APPROVED** [review]
Nice PR description template.

**Review by mainred — CHANGES_REQUESTED** [review]
We need to cache windows azuredisk image as well.

**Comment by mainred** [comment]
cc @ZeroMagic as well, we need to cache azuredisk/file image for windows and linux both.

**Review by mainred — APPROVED** [review]

**Comment by andyzhangx** [comment]
@AbelHu seems `AKS Windows VHD Build - PR check-in gate` is broken

https://msazure.visualstudio.com/09706533-03bf-4b43-9a9b-b49c75429646/_apis/build/builds/53745639/logs/29
```
2022-04-01T09:02:35.7531715Z /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
2022-04-01T09:02:35.7533794Z   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2022-04-01T09:02:35.8523578Z + [[ default != \d\e\f\a\u\l\t ]]
2022-04-01T09:02:35.8524998Z + [[ -n '' ]]
2022-04-01T09:02:35.8525689Z + [[ -n '' ]]
2022-04-01T09:02:35.8526351Z + [[ -n '' ]]
2022-04-01T09:02:35.8527026Z + '[' == arm64 ']'
2022-04-01T09:02:35.8527605Z ./vhdbuilder/packer/cleanup.sh: line 74: [: ==: unary operator expected
```

**Comment by AbelHu** [comment]
@andyzhangx it is a known issue and @shiqiantao is investigating it.

**Comment by AbelHu** [comment]
@andyzhangx Are the updated versions using currently?

**Comment by andyzhangx** [comment]
> @andyzhangx Are the updated versions using currently?

@AbelHu yes, I forgot to update csi driver images on Windows in the before, this PR added all missing images.

**Review by AbelHu — APPROVED** [review]

**Pull request merged**
