### PR TITLE
cache CNS v1.4.52 and v1.5.17

### PR DESCRIPTION
**Pull request by rbtr**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Caches new CNS versions with a memory leak fix

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by AbelHu** [comment]
Code LGTM. You need to fix the failed tests.

**Comment by rbtr** [comment]
updated message for commitlint check, but the UT check failure looks like coveralls is misconfigured. unrelated and not something i can fix

**Review by tyler-lloyd — APPROVED** [review]
lgtm

**Comment by rbtr** [comment]
@cameronmeissner can you help me get this change in?

**Review by juan-lee — APPROVED** [review]

**Pull request merged**
