### PR TITLE
Azure CNI to 1.2.6 also cache swift azure cni

### PR DESCRIPTION
**Pull request by paulgmiller**
Just published in this build def
https://dev.azure.com/AzureContainerUpstream/Kubernetes/_build/results?buildId=18234&view=results

### CODE REVIEW

**Comment by paulgmiller** [comment]
@mattstam  give me a re-review. Moved this over to get vhd pipeliens to pass and also found an issue where swift doesn't have older versions.

**Review by mattstam — APPROVED** [review]
Re-approving

**Comment by paulgmiller** [comment]
Got a ++ echo -e '\ntestFilesDownloaded:Error:' File /opt/cni/downloads/azure-vnet-cni-linux-amd64-v1.1.8.tgz does not exist
Which is strange. Might jsut remove.1.18 but checking why that doesn't exist.

**Comment by paulgmiller** [comment]
> Got a ++ echo -e '\ntestFilesDownloaded:Error:' File /opt/cni/downloads/azure-vnet-cni-linux-amd64-v1.1.8.tgz does not exist
> Which is strange. Might jsut remove.1.18 but checking why that doesn't exist.

Aha! found we have unittests now which is great!

**Review by adilliadil — APPROVED** [review]
lgtm

**Review by AbelHu — APPROVED** [review]

**Pull request merged**
