### PR TITLE
chore: update go-dev to 1.34.0

### PR DESCRIPTION
**Pull request by alexeldeib**
should get us a newer packer version, I think?

### CODE REVIEW

**Review by ganeshkumar5699 — APPROVED** [review]
Checked [go-dev's index url](https://mcrflowprodcentralus.data.mcr.microsoft.com/mcrprod/oss/azcu/go-dev?P1=1630453513&P2=1&P3=1&P4=0j65WkhfCMiieHD5xL9%2BqH4bvRUEti%2B7OBcux4Fmt6U%3D&se=2021-08-31T23%3A45%3A13Z&sig=1%2Bhb8mmbcxgfwenFOpiiMbSQ1IHSVRzaoVWGlDGf0E0%3D&sp=r&sr=b&sv=2015-02-21) to confirm that v1.34.0 is the latest version. 
Lgtm.

**Comment by alexeldeib** [comment]
dunno why linux VHD isn't triggering? I ran it manually https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=46257314&view=logs&j=e87678bc-3b03-5f2b-4494-ebb72fdaf05d

**Comment by alexeldeib** [comment]
ah, we had path filters on our triggers: https://msazure.visualstudio.com/CloudNativeCompute/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=119535&view=Tab_Triggers

**Comment by alexeldeib** [comment]
there goes the linux vhd :)

**Pull request merged**
