### PR TITLE
remove deprecate flag keep-terminated-pod-volumes

### PR DESCRIPTION
**Pull request by wenhug**
**What type of PR is this?**

/kind feature

/kind deprecation

**What this PR does / why we need it**:
Romove deprecate flag `--keep-terminated-pod-volumes`
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:

```
none
```

### CODE REVIEW

**Comment by cameronmeissner** [comment]
has there already been a change on the RP side for removing this flag?

**Comment by wenhug** [comment]
RP will delete this flag in pr that supports 1.31 version.  This flag has been deprecated since 2017

**Comment by wenhug** [comment]
I'm not sure about the sequential dependency between this part of the change and the change of the RP, and how to change the testdata of the RP, can you help to explain it?

**Comment by cameronmeissner** [comment]
it looks like your changes are only removing hard-coded references to this flag from testing code, which should be fine to merge right now

it sounds like we're letting RP dictate when to correctly set the flag, so I think we're fine in terms of dependency ordering regardless

**Review by cameronmeissner — APPROVED** [review]

**Pull request merged**
