### PR TITLE
Tienle/confcom air gapped

### PR DESCRIPTION
**Pull request by tle15**
There are two components of our confcom AKS addon: device-plugin and quote-helper. Device-plugin has been baked in VHD, this RP is to bake quote-helper. This comes as the requirement for onboarding confcom to air-gapped regions.

### CODE REVIEW

**Review by adilliadil — COMMENTED** [review]
Can you also please update the linux-vhd-content-test.sh file

**Comment by tle15** [comment]
@adilliadil : Updated linux-vhd-content-test.sh

**Comment by adilliadil** [comment]
> @adilliadil : Updated linux-vhd-content-test.sh

Just talked offline, sgx is for gen2 only, currently, our tests don't support specific testing per SKU. I will make changes so that we're more flexible with the tests and can also test based on SKU. But for now the changes in the lniux-vhd-content-test.sh should be removed since they will break the tests. Sorry for asking to change the test file and revert it.

**Comment by tle15** [comment]
@adilliadil: Reverted linux-vhd-content-test.sh

**Review by adilliadil — APPROVED** [review]
lgtm

**Pull request merged**
