### PR TITLE
chore: cache cloud node manager windows host process images

### PR DESCRIPTION
**Pull request by mainred**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

cache cloud node manager windows host process images

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:

```
none
```

### CODE REVIEW

**Comment by AbelHu** [comment]
@mainred it seems like that it failed in pulling the images
https://github.com/Azure/AgentBaker/actions/runs/11247317612/job/31270598215?pr=5040

**Comment by mainred** [comment]
v1.27.21-windows-hpc is still being published. Let me re-trigger the check when the image is ready.
Starting this PR early to check if the vhd disk size is empty to hold these images.

**Comment by AbelHu** [comment]
@ShiqianTao will start to build new vhds. @mainred Please help to fix it ASAP so it can be included in next VHDs.

**Comment by mainred** [comment]
@AbelHu  Thanks for the heads-up. The publish is done and the checks should be green now.

**Comment by mainred** [comment]
ping @AbelHu @ShiqianTao to take a look.

**Review by ShiqianTao — APPROVED** [review]

**Pull request merged**
