### PR TITLE
chore: Update AKS Windows images to 2022.07C

### PR DESCRIPTION
**Pull request by ShiqianTao**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Update AKS Windows images to 2022.07C. Reference: https://github.com/Azure/AgentBaker/pull/1997
**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [x] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
Update the latest Windows image versions with 2022.7C
- Windows2019 docker: 17763.3232.220722
- Windows2019 contaienrd: 17763.3232.220722
- Windows2022 containerd: 20348.859.220722
```

### CODE REVIEW

**Comment by AbelHu** [comment]
Please add the release note in this PR and update our vhd wiki

**Comment by ShiqianTao** [comment]
> Please add the release note in this PR and update our vhd wiki

Hi @AbelHu , 1. There were three release notes in this PR. 2. What is the VHD wiki that I need to update?

**Comment by AbelHu** [comment]
Update the "Release note:" in this PR. Update our VHD wiki page "Add `Release note:` in PR description when creating PR against AgentBaker to add release notes"
image

**Comment by ShiqianTao** [comment]
> Update the "Release note:" in this PR. Update our VHD wiki page "Add `Release note:` in PR description when creating PR against AgentBaker to add release notes" image

I See. Thanks for your guidance @AbelHu . Updated them.

**Review by AbelHu — APPROVED** [review]

**Pull request merged**
