### PR TITLE
chore: update pause image to 1.4.1

### PR DESCRIPTION
**Pull request by AbelHu**
1. update pause image to 1.4.1: https://github.com/Azure/aks-engine/pull/4273
2. fix warning in running "make generate"

### CODE REVIEW

**Comment by mainred** [comment]
Do we need to cache the image?

**Comment by AbelHu** [comment]
> Do we need to cache the image?

Yes. Please see it [here](https://github.com/Azure/AgentBaker/pull/601/files#diff-04034f02ed12d75260f68e923224ad7ebbb6ed74d9cb550c0a542a4412a5698d)

**Comment by mainred** [comment]
Thanks for this change, but please let's wait until we have an answer from upstream to the influence and change of the new pause image
https://github.com/Azure/aks-engine/pull/4273#issuecomment-782983806

**Review by mainred — APPROVED** [review]
LGTM

**Review by xuto2 — APPROVED** [review]

**Pull request merged**
