### PR TITLE
chore: cleanup abe2e files

### PR DESCRIPTION
**Pull request by cameronmeissner**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

removes files in ab e2e that are no longer used, moves windows-related e2e files to a dedicated directory, renames some old files accordingly

**Which issue(s) this PR fixes**:

Fixes #

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by cameronmeissner** [comment]
@AbelHu @junjiezhang1997 would you mind taking a look?

**Review by junjiezhang1997 — APPROVED** [review]
LGTM. Thanks very much for the clean up!

**Comment by cameronmeissner** [comment]
@AbelHu  I spoke a bit about this with Ace - we're thinking moving things around like this could be fine for now until Windows E2E is run in Go alongside Linux (which is something I can also take an initial stab at if time permits and you're prioritizing other things).

**Comment by AbelHu** [comment]
Please resolve the conflict in `e2e/e2e_test.go` and rerun `Agentbaker Windows E2E`

**Review by alexeldeib — APPROVED** [review]
lgtm, wonder if we can converge windows on Go?

**Comment by alexeldeib** [comment]
commit lint doesn't like something - rebase?

**Comment by cameronmeissner** [comment]
> 

was thinking this could be a good thing to add to the board

**Pull request merged**
