### PR TITLE
replace NPM v1.4.12 with 1.4.18

### PR DESCRIPTION
**Pull request by huntergregory**
v1.4.16 has baked in canary for ~2 weeks, and 1.4.18 is very similar to it

### CODE REVIEW

**Comment by mattstam** [comment]
According to RP change, `v1.4.18` is already whitelisted and will be merged before this gets vendored. In the future this should be added first (you also won't need whitelisting this way).

**Review by mattstam — APPROVED** [review]

**Comment by vakalapa** [comment]
@andyliuliming  Can you help merge this in ?

**Comment by mattstam** [comment]
@vakalapa I can merge just had merge with most recent master and wait for PR check-in now

**Comment by mattstam** [comment]
Okay saw it pass once so just merging after this 😄

**Pull request merged**
