### PR TITLE
Add node fqdn to Kubelet certificate

### PR DESCRIPTION
**Pull request by phealy**
Adds the node FQDN to the Kubelet certificate.

### CODE REVIEW

**Comment by phealy** [comment]
Doesn't work yet - do not merge.

**Comment by phealy** [comment]
So this works in that the commands are run, but `hostname -f` isn't returning the FQDN this early in the build cycle. Any thoughts on a good way to fix this, @UtheMan @alexeldeib @anujmaheshwari1?

**Comment by alexeldeib** [comment]
@phealy just doing some housekeeping -- what do you want to do with this one? don't think we found a good way in the short term, might be worth just waiting for us to have all the stuff for proper CSR bootstrapping?

**Comment by cameronmeissner** [comment]
no longer needed

**Pull request closed without merging**
