### PR TITLE
chore: Add new k8s hotfix versions for Windows

### PR DESCRIPTION
**Pull request by AbelHu**
Add new k8s hotfix versions for Windows with [Automated cherry pick of #104384: fix: skip case sensitivity when checking Azure NSG rules #104382: fix: ensure InstanceShutdownByProviderID return false for by feiskyer · Pull Request #104448](https://github.com/kubernetes/kubernetes/pull/1044480)

### CODE REVIEW

**Review by mainred — APPROVED** [review]

**Review by ganeshkumar5699 — COMMENTED** [review]
Would this need an update to kube-proxy as well? In that case, https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/packer/kube-proxy-images.json also needs to be updated. 

From the email thread, it seems like only kube-controller-manager needs to be updated so I assume kube-proxy update is not needed. Lgtm in that case. 

Thanks for updating Linux versions in this same PR as well!

**Comment by AbelHu** [comment]
> kube-controller-manager

I think that the hotfix only has the change in kube-controller-manager so we do not need to update kube-proxy.

**Review by ganeshkumar5699 — APPROVED** [review]

**Comment by feiskyer** [comment]
@AbelHu do we still need those updates?

**Comment by AbelHu** [comment]
> @AbelHu do we still need those updates?

Yes. We always try to keep the kube binaries to the latest hotfix versions.

**Comment by AbelHu** [comment]
@pengfei, you are right. Since I do not want to update k8s binary versions in AKS. I will abandon this

**Pull request closed without merging**
